[package]
name = "window"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-iterator = "1.2.0"
enum-map = "2.4.2"

rodio = "0.16.0"


[dependencies.sdl2]
version = "0.32.1"
features = ["ttf"]


